### ISSUE TITLE
Add link to partner / supporter logos at the bottom of main page

### ISSUE THREAD

**Issue by MaximilianVomhof** [opensource-construction/website#87]
As a user, I want to click on the logos (or a separate button) and be forwarded in a separate page to the organisation behind the logo

**Comment by maveric1977** [comment]
Based on the discussion with @MaximilianVomhof , I will also restyle the logos a bit, make them more dynamic and add industry partners as well to the logos list as a separate section.

**Comment by MaximilianVomhof** [comment]
@maveric1977 please move bauendigital zu community partner

And remove thatopencompany / speckle / builders (wrong logo) from the industry partners

**Comment by MaximilianVomhof** [comment]
@maveric1977 and for the team section:
Christian: change from local lead Copenhagen to country lead Denmark 
Same for Karim with UK
Ryan: lead infrastructure & team copenhagen
