### ISSUE TITLE
URL does not match content of site

### ISSUE THREAD

**Issue by MaximilianVomhof** [opensource-construction/website#95]
<img width="1011" alt="Bildschirmfoto 2024-07-10 um 19 39 57" src="https://github.com/opensource-construction/website/assets/126971887/844a8d14-c822-4dfb-8d19-56bc3d4b61dd">

**Comment by n0rdlicht** [comment]
@MaximilianVomhof the file names (used to generate the url slug) got switched somehow, now it's fixed :)
